export const data = [{
    "status": "SUCCESS",
    "data": [
        {
            "id": 1,
            "title": "خدمات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },
        {
            "id": 101,
            "title": "آموزش و تحقیقات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 1,
            "parent__title": "خدمات",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 102,
            "title": "آموزش رسمی غیر دانشگاهی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 101,
            "parent__title": "آموزش و تحقیقات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 103,
            "title": "کودکستان غیر دولتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 102,
            "parent__title": "آموزش رسمی غیر دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 104,
            "title": "مدرسه غیر دولتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 102,
            "parent__title": "آموزش رسمی غیر دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 105,
            "title": "آموزش رسمی دانشگاهی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 101,
            "parent__title": "آموزش و تحقیقات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 106,
            "title": "موسسه آموزش عالی آزاد",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 105,
            "parent__title": "آموزش رسمی دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 107,
            "title": "مؤسسه آموزش عالی غیر دولتی (حضوری و مجازی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 105,
            "parent__title": "آموزش رسمی دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 108,
            "title": "آموزش مهارتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 101,
            "parent__title": "آموزش و تحقیقات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 109,
            "title": "مرکز آموزش غیر دولتی (زبان، علمی و کنکور)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 108,
            "parent__title": "آموزش مهارتی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 110,
            "title": "تدریس خصوصی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 108,
            "parent__title": "آموزش مهارتی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 2,
            "title": "سلامت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },
        {
            "id": 201,
            "title": "آموزش و ارتقا سلامت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 2,
            "parent__title": "سلامت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 202,
            "title": "آموزشگاه بهداشت اصناف",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 201,
            "parent__title": "آموزش و ارتقا سلامت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 203,
            "title": "مؤسسه خدمات آموزشی در امور فرآورده های آرایشی و بهداشتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 201,
            "parent__title": "آموزش و ارتقا سلامت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 204,
            "title": "بهداشت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 2,
            "parent__title": "سلامت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 205,
            "title": "دفتر خدمات سلامت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 204,
            "parent__title": "بهداشت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 206,
            "title": "خدمات بهداشت حرفه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 204,
            "parent__title": "بهداشت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 207,
            "title": "درمان کلینیکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 2,
            "parent__title": "سلامت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 208,
            "title": "بیمارستان",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 207,
            "parent__title": "درمان کلینیکی",
            "tag": "1",
            "comment": "",
            "link": ""
        },
        {
            "id": 209,
            "title": "درمانگاه عمومی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 207,
            "parent__title": "درمان کلینیکی",
            "tag": "1",
            "comment": "",
            "link": ""
        },
        {
            "id": 3,
            "title": "امور اجتماعی و بهزیستی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },
        {
            "id": 301,
            "title": "نگهداری شبانه روزی کودکان بی سرپرست و خیابانی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 3,
            "parent__title": "امور اجتماعی و بهزیستی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 302,
            "title": "خانه نوباوگان",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 301,
            "parent__title": "نگهداری شبانه روزی کودکان بی سرپرست و خیابانی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 303,
            "title": "خانه کودکان و نوجوانان (پسران 13 تا 18 سال)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 301,
            "parent__title": "نگهداری شبانه روزی کودکان بی سرپرست و خیابانی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 304,
            "title": "سلامت دختران و زنان",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 3,
            "parent__title": "امور اجتماعی و بهزیستی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 305,
            "title": "خانه امن زنان تحت خشونت خانگی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 304,
            "parent__title": "سلامت دختران و زنان",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 306,
            "title": "مرکز حمایت و توانمندسازی زنان آسیب دیده اجتماعی (راه نوین)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 304,
            "parent__title": "سلامت دختران و زنان",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 307,
            "title": "خدمات بهزیستی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 3,
            "parent__title": "امور اجتماعی و بهزیستی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 308,
            "title": "مجتمع خدمات بهزیستی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 307,
            "parent__title": "خدمات بهزیستی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 309,
            "title": "مرکز مثبت زندگی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 307,
            "parent__title": "خدمات بهزیستی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 4,
            "title": "کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },
        {
            "id": 401,
            "title": "تولیدات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 4,
            "parent__title": "کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 402,
            "title": "گلخانه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 401,
            "parent__title": "تولیدات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 403,
            "title": "شهرک گلخانه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 402,
            "parent__title": "گلخانه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 404,
            "title": "واحد گلخانه ای (مستقر در شهرک کشاورزی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 402,
            "parent__title": "گلخانه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 405,
            "title": "قارچ خوراکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 401,
            "parent__title": "تولیدات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 406,
            "title": "شهرک قارچ خوراکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 405,
            "parent__title": "قارچ خوراکی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 407,
            "title": "واحد قارچ خوراکی (مستقر در شهرک کشاورزی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 405,
            "parent__title": "قارچ خوراکی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 408,
            "title": "سایر محصولات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 401,
            "parent__title": "تولیدات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 409,
            "title": "پرورش خانگی گلمحمدی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 408,
            "parent__title": "سایر محصولات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 410,
            "title": "تولید خانگی آلوئه ورا",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 408,
            "parent__title": "سایر محصولات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 411,
            "title": "خدمات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 4,
            "parent__title": "کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 412,
            "title": "حفظ نباتات و کنترل آفات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 411,
            "parent__title": "خدمات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 413,
            "title": "آزمایشگاه تشخیص آفات و بیماری های گیاهی (کلینیک های گیاه پزشکی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 412,
            "parent__title": "حفظ نباتات و کنترل آفات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 414,
            "title": "تولید عوامل ماکرو ارگانیسم کنترل بیولوژیک آفات (انسکتاریوم گیاه پزشکی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 412,
            "parent__title": "حفظ نباتات و کنترل آفات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 415,
            "title": "بذر و نهال",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 411,
            "parent__title": "خدمات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 416,
            "title": "واحد تولید نهال",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 415,
            "parent__title": "بذر و نهال",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 417,
            "title": "واحد تولید بذر اسپان قارچ خوراکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 415,
            "parent__title": "بذر و نهال",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 418,
            "title": "مکانیزاسیون و ماشین‌آلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 411,
            "parent__title": "خدمات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 419,
            "title": "شرکت فنی تخصصی مکانیزاسیون",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 418,
            "parent__title": "مکانیزاسیون و ماشین‌آلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 420,
            "title": "خرده فروشی ادوات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 418,
            "parent__title": "مکانیزاسیون و ماشین‌آلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 421,
            "title": "تولیدات دامی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 4,
            "parent__title": "کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 422,
            "title": "دام",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 421,
            "parent__title": "تولیدات دامی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 423,
            "title": "پرورش صنعتی و نیمه صنعتی گوسفند و بز",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 422,
            "parent__title": "دام",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 424,
            "title": "پرورش صنعتی و نیمه صنعتی گاو و گاومیش",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 422,
            "parent__title": "دام",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 425,
            "title": "طیور",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 421,
            "parent__title": "تولیدات دامی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 426,
            "title": "پرورش صنعتی و نیمه صنعتی مرغ و طیور",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 425,
            "parent__title": "طیور",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 427,
            "title": "پرورش صنعتی و نیمه صنعتی جوجه یکروزه مرغ",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 425,
            "parent__title": "طیور",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 428,
            "title": "شیلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 421,
            "parent__title": "تولیدات دامی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 429,
            "title": "صید و صیادی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 428,
            "parent__title": "شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 430,
            "title": "پرورش صنعتی و نیمه صنعتی ماهی در قفس",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 428,
            "parent__title": "شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 501,
            "title": "صنایع ماشین‌آلات و تجهیزات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 5,
            "parent__title": "صنعت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 502,
            "title": "ماشین آلات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 501,
            "parent__title": "صنایع ماشین‌آلات و تجهیزات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 503,
            "title": "تولید قطعات و ماشین آلات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 502,
            "parent__title": "ماشین آلات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 504,
            "title": "تولید وتعمیر ابزار کشاورزی و باغبانی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 502,
            "parent__title": "ماشین آلات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 505,
            "title": "ماشین آلات پرورش دام و شیلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 501,
            "parent__title": "صنایع ماشین‌آلات و تجهیزات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 506,
            "title": "تولید قطعات و ماشین آلات پرورش دام و شیلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 505,
            "parent__title": "ماشین آلات پرورش دام و شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 507,
            "title": "تولید وتعمیر ماشین آلات مرغداری",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 505,
            "parent__title": "ماشین آلات پرورش دام و شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 508,
            "title": "ماشین آلات مهندسی، عمرانی و معدنی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 501,
            "parent__title": "صنایع ماشین‌آلات و تجهیزات",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 509,
            "title": "تولید قطعات و ماشین آلات پروژه عمرانی و معدنی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 508,
            "parent__title": "ماشین آلات مهندسی، عمرانی و معدنی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 510,
            "title": "تولید و تعمیر ماشین آلات راهسازی ساختمانی و معدنی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 508,
            "parent__title": "ماشین آلات مهندسی، عمرانی و معدنی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 511,
            "title": "صنایع برقی و الکترونیکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 5,
            "parent__title": "صنعت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 512,
            "title": "قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 511,
            "parent__title": "صنایع برقی و الکترونیکی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 513,
            "title": "تولید قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 512,
            "parent__title": "قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 514,
            "title": "تولید قطعات گوشی تلفن، تلفن سانترال الکترونیکی و دیجیتالی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 512,
            "parent__title": "قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 515,
            "title": "قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 511,
            "parent__title": "صنایع برقی و الکترونیکی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 516,
            "title": "تولید قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 515,
            "parent__title": "قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 517,
            "title": "تولید و مونتاژ تجهیزات جانبی رایانه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 516,
            "parent__title": "تولید قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 518,
            "title": "ابزار دقیق، اندازه گیری و ساعت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 511,
            "parent__title": "صنایع برقی و الکترونیکی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 519,
            "title": "تولید ابزار دقیق، اندازه گیری و ساعت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 518,
            "parent__title": "ابزار دقیق، اندازه گیری و ساعت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 520,
            "title": "تولید و تعمیر انواع ترازو",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 518,
            "parent__title": "ابزار دقیق، اندازه گیری و ساعت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 521,
            "title": "صنایع منسوجات و پوشاک",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 5,
            "parent__title": "صنعت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 522,
            "title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 521,
            "parent__title": "صنایع منسوجات و پوشاک",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 523,
            "title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 522,
            "parent__title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 524,
            "title": "تولید و فروش انواع پنبه ،اسفنج ،الیاف پشم و کرک و پر",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 522,
            "parent__title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 525,
            "title": "بافندگی منسوجات و تولید پارچه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 521,
            "parent__title": "صنایع منسوجات و پوشاک",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 526,
            "title": "بافندگی منسوجات و تولید پارچه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 525,
            "parent__title": "بافندگی منسوجات و تولید پارچه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 527,
            "title": "بافندگی انواع منسوجات به صورت ماشینی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 525,
            "parent__title": "بافندگی منسوجات و تولید پارچه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 528,
            "title": "تکمیل منسوجات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 521,
            "parent__title": "صنایع منسوجات و پوشاک",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 529,
            "title": "تکمیل منسوجات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 528,
            "parent__title": "تکمیل منسوجات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 530,
            "title": "پلیسه انواع لباس",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 528,
            "parent__title": "تکمیل منسوجات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },


    ],
    "total_count": 32
}];