export const data = [{
    "status": "SUCCESS",
    "data": [
        {
            "id": 1,
            "title": "خدمات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },
        {
            "id": 101,
            "title": "آموزش و تحقیقات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 1,
            "parent__title": "خدمات",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 102,
            "title": "آموزش رسمی غیر دانشگاهی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 101,
            "parent__title": "آموزش و تحقیقات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 103,
            "title": "کودکستان غیر دولتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 102,
            "parent__title": "آموزش رسمی غیر دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 104,
            "title": "مدرسه غیر دولتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 102,
            "parent__title": "آموزش رسمی غیر دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 105,
            "title": "آموزش رسمی دانشگاهی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 101,
            "parent__title": "آموزش و تحقیقات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 106,
            "title": "موسسه آموزش عالی آزاد",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 105,
            "parent__title": "آموزش رسمی دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 107,
            "title": "مؤسسه آموزش عالی غیر دولتی (حضوری و مجازی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 105,
            "parent__title": "آموزش رسمی دانشگاهی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 108,
            "title": "آموزش مهارتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 101,
            "parent__title": "آموزش و تحقیقات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 109,
            "title": "مرکز آموزش غیر دولتی (زبان، علمی و کنکور)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 108,
            "parent__title": "آموزش مهارتی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 110,
            "title": "تدریس خصوصی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 108,
            "parent__title": "آموزش مهارتی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },

        {
            "id": 111,
            "title": "سلامت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 1,
            "parent__title": "خدمات",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 112,
            "title": "آموزش و ارتقا سلامت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 111,
            "parent__title": "سلامت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 113,
            "title": "آموزشگاه بهداشت اصناف",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 112,
            "parent__title": "آموزش و ارتقا سلامت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 114,
            "title": "مؤسسه خدمات آموزشی در امور فرآورده های آرایشی و بهداشتی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 112,
            "parent__title": "آموزش و ارتقا سلامت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 115,
            "title": "بهداشت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 111,
            "parent__title": "سلامت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 116,
            "title": "دفتر خدمات سلامت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 115,
            "parent__title": "بهداشت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 117,
            "title": "خدمات بهداشت حرفه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 115,
            "parent__title": "بهداشت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 118,
            "title": "درمان کلینیکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 111,
            "parent__title": "سلامت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 119,
            "title": "بیمارستان",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 118,
            "parent__title": "درمان کلینیکی",
            "tag": "1",
            "comment": "",
            "link": ""
        },
        {
            "id": 120,
            "title": "درمانگاه عمومی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 118,
            "parent__title": "درمان کلینیکی",
            "tag": "1",
            "comment": "",
            "link": ""
        },
        {
            "id": 121,
            "title": "امور اجتماعی و بهزیستی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 1,
            "parent__title": "خدمات",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 122,
            "title": "نگهداری شبانه روزی کودکان بی سرپرست و خیابانی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 121,
            "parent__title": "امور اجتماعی و بهزیستی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 123,
            "title": "خانه نوباوگان",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 122,
            "parent__title": "نگهداری شبانه روزی کودکان بی سرپرست و خیابانی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 124,
            "title": "خانه کودکان و نوجوانان (پسران 13 تا 18 سال)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 122,
            "parent__title": "نگهداری شبانه روزی کودکان بی سرپرست و خیابانی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 125,
            "title": "سلامت دختران و زنان",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 121,
            "parent__title": "امور اجتماعی و بهزیستی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 126,
            "title": "خانه امن زنان تحت خشونت خانگی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 125,
            "parent__title": "سلامت دختران و زنان",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 127,
            "title": "مرکز حمایت و توانمندسازی زنان آسیب دیده اجتماعی (راه نوین)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 125,
            "parent__title": "سلامت دختران و زنان",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 128,
            "title": "خدمات بهزیستی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 121,
            "parent__title": "امور اجتماعی و بهزیستی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 129,
            "title": "مجتمع خدمات بهزیستی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 128,
            "parent__title": "خدمات بهزیستی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 130,
            "title": "مرکز مثبت زندگی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 128,
            "parent__title": "خدمات بهزیستی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 2,
            "title": "کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },
        {
            "id": 201,
            "title": "تولیدات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 2,
            "parent__title": "کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 202,
            "title": "گلخانه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 201,
            "parent__title": "تولیدات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 203,
            "title": "شهرک گلخانه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 202,
            "parent__title": "گلخانه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 204,
            "title": "واحد گلخانه ای (مستقر در شهرک کشاورزی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 202,
            "parent__title": "گلخانه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 205,
            "title": "قارچ خوراکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 201,
            "parent__title": "تولیدات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 206,
            "title": "شهرک قارچ خوراکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 205,
            "parent__title": "قارچ خوراکی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 207,
            "title": "واحد قارچ خوراکی (مستقر در شهرک کشاورزی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 205,
            "parent__title": "قارچ خوراکی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 208,
            "title": "سایر محصولات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 201,
            "parent__title": "تولیدات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 209,
            "title": "پرورش خانگی گلمحمدی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 208,
            "parent__title": "سایر محصولات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 210,
            "title": "تولید خانگی آلوئه ورا",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 208,
            "parent__title": "سایر محصولات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 211,
            "title": "خدمات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 2,
            "parent__title": "کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 212,
            "title": "حفظ نباتات و کنترل آفات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 211,
            "parent__title": "خدمات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 213,
            "title": "آزمایشگاه تشخیص آفات و بیماری های گیاهی (کلینیک های گیاه پزشکی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 212,
            "parent__title": "حفظ نباتات و کنترل آفات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 214,
            "title": "تولید عوامل ماکرو ارگانیسم کنترل بیولوژیک آفات (انسکتاریوم گیاه پزشکی)",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 212,
            "parent__title": "حفظ نباتات و کنترل آفات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 215,
            "title": "بذر و نهال",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 211,
            "parent__title": "خدمات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 216,
            "title": "واحد تولید نهال",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 215,
            "parent__title": "بذر و نهال",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 217,
            "title": "واحد تولید بذر اسپان قارچ خوراکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 215,
            "parent__title": "بذر و نهال",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 218,
            "title": "مکانیزاسیون و ماشین‌آلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 211,
            "parent__title": "خدمات کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 219,
            "title": "شرکت فنی تخصصی مکانیزاسیون",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 218,
            "parent__title": "مکانیزاسیون و ماشین‌آلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 220,
            "title": "خرده فروشی ادوات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 218,
            "parent__title": "مکانیزاسیون و ماشین‌آلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 221,
            "title": "تولیدات دامی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 2,
            "parent__title": "کشاورزی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 222,
            "title": "دام",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 221,
            "parent__title": "تولیدات دامی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 223,
            "title": "پرورش صنعتی و نیمه صنعتی گوسفند و بز",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 222,
            "parent__title": "دام",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 224,
            "title": "پرورش صنعتی و نیمه صنعتی گاو و گاومیش",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 222,
            "parent__title": "دام",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 225,
            "title": "طیور",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 221,
            "parent__title": "تولیدات دامی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 226,
            "title": "پرورش صنعتی و نیمه صنعتی مرغ و طیور",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 225,
            "parent__title": "طیور",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 227,
            "title": "پرورش صنعتی و نیمه صنعتی جوجه یکروزه مرغ",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 225,
            "parent__title": "طیور",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 228,
            "title": "شیلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 221,
            "parent__title": "تولیدات دامی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 229,
            "title": "صید و صیادی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 228,
            "parent__title": "شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 230,
            "title": "پرورش صنعتی و نیمه صنعتی ماهی در قفس",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 228,
            "parent__title": "شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 3,
            "title": "صنعت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": null,
            "parent__title": null,
            "tag": "1",
            "comment": ""
        },

        {
            "id": 301,
            "title": "صنایع ماشین‌آلات و تجهیزات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 3,
            "parent__title": "صنعت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 302,
            "title": "ماشین آلات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 301,
            "parent__title": "صنایع ماشین‌آلات و تجهیزات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 303,
            "title": "تولید قطعات و ماشین آلات کشاورزی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 302,
            "parent__title": "ماشین آلات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 304,
            "title": "تولید وتعمیر ابزار کشاورزی و باغبانی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 302,
            "parent__title": "ماشین آلات کشاورزی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 305,
            "title": "ماشین آلات پرورش دام و شیلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 301,
            "parent__title": "صنایع ماشین‌آلات و تجهیزات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 306,
            "title": "تولید قطعات و ماشین آلات پرورش دام و شیلات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 305,
            "parent__title": "ماشین آلات پرورش دام و شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 307,
            "title": "تولید وتعمیر ماشین آلات مرغداری",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 305,
            "parent__title": "ماشین آلات پرورش دام و شیلات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 308,
            "title": "ماشین آلات مهندسی، عمرانی و معدنی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 301,
            "parent__title": "صنایع ماشین‌آلات و تجهیزات",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 309,
            "title": "تولید قطعات و ماشین آلات پروژه عمرانی و معدنی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 308,
            "parent__title": "ماشین آلات مهندسی، عمرانی و معدنی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 310,
            "title": "تولید و تعمیر ماشین آلات راهسازی ساختمانی و معدنی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 308,
            "parent__title": "ماشین آلات مهندسی، عمرانی و معدنی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 311,
            "title": "صنایع برقی و الکترونیکی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 3,
            "parent__title": "صنعت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 312,
            "title": "قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 311,
            "parent__title": "صنایع برقی و الکترونیکی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 313,
            "title": "تولید قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 312,
            "parent__title": "قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 314,
            "title": "تولید قطعات گوشی تلفن، تلفن سانترال الکترونیکی و دیجیتالی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 312,
            "parent__title": "قطعات، لوازم جانبی و تجهیزات ارتباطی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 315,
            "title": "قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 311,
            "parent__title": "صنایع برقی و الکترونیکی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 316,
            "title": "تولید قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 315,
            "parent__title": "قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 317,
            "title": "تولید و مونتاژ تجهیزات جانبی رایانه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 315,
            "parent__title": "تولید قطعات، لوازم جانبی و تجهیزات رایانه ای",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 318,
            "title": "ابزار دقیق، اندازه گیری و ساعت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 311,
            "parent__title": "صنایع برقی و الکترونیکی",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 319,
            "title": "تولید ابزار دقیق، اندازه گیری و ساعت",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 318,
            "parent__title": "ابزار دقیق، اندازه گیری و ساعت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 320,
            "title": "تولید و تعمیر انواع ترازو",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 318,
            "parent__title": "ابزار دقیق، اندازه گیری و ساعت",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 321,
            "title": "صنایع منسوجات و پوشاک",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 3,
            "parent__title": "صنعت",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 322,
            "title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 321,
            "parent__title": "صنایع منسوجات و پوشاک",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 323,
            "title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 322,
            "parent__title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 324,
            "title": "تولید و فروش انواع پنبه ،اسفنج ،الیاف پشم و کرک و پر",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 322,
            "parent__title": "آماده‌سازی و ریسندگی الیاف نساجی",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 325,
            "title": "بافندگی منسوجات و تولید پارچه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 321,
            "parent__title": "صنایع منسوجات و پوشاک",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 326,
            "title": "بافندگی منسوجات و تولید پارچه",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 325,
            "parent__title": "بافندگی منسوجات و تولید پارچه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 327,
            "title": "بافندگی انواع منسوجات به صورت ماشینی",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 325,
            "parent__title": "بافندگی منسوجات و تولید پارچه",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 328,
            "title": "تکمیل منسوجات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 321,
            "parent__title": "صنایع منسوجات و پوشاک",
            "tag": "1",
            "comment": ""
        },
        {
            "id": 329,
            "title": "تکمیل منسوجات",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 328,
            "parent__title": "تکمیل منسوجات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },
        {
            "id": 330,
            "title": "پلیسه انواع لباس",
            "code": "",
            "description": "",
            "is_active": true,
            "catalog": 1,
            "parent__id": 328,
            "parent__title": "تکمیل منسوجات",
            "tag": "1",
            "comment": "",
            "link": "https://www.google.com/"
        },


    ],
    "total_count": 33
}];